title: "ToKoDraw - Blender Layer System"
description: "Manuel d'utilisation"

theme: null

sass:
  sass_dir: assets/css
  style: compressed

markdown: kramdown
kramdown:
  input: GFM

include:
  - assets
  - _layouts
